name: Running gtests, collecting coverage (push master)

on:
  push:
    branches: [ main ]

env:
  LINE_COV_GATE: 0
  MCDC_COV_GATE: 0
  DTP_PROJECT: ATM_testing

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: self-hosted
    continue-on-error: true

    steps:
    - uses: actions/checkout@v4

    - name: Set build id
      shell: bash
      working-directory: ${{github.workspace}}
      run: echo "build_id=build-$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV

    # Set up properties file
    - name: set up properties file
      run: |
        echo  -e "\n~~~\nSetting up and creating cpptestcli.properties file.\n"
        echo $"
        parasoft.eula.accepted=true
        cpptest.license.network.edition=server_compliance_edition
        license.network.enabled=true
        license.network.auth.enabled=true
        license.network.password=${{secrets.LSS_PASS}}
        license.network.url=${{secrets.LSS_URL}}
        license.network.user=${{vars.LSS_USER}}
        dtp.url=${{secrets.DTP_URL}}
        dtp.user=${{vars.LSS_USER}}
        dtp.password=${{secrets.LSS_PASS}}
        dtp.project=ATM
        build.id=${{env.build_id}}
        scope.scontrol=true
        report.suppressed_msgs=true
        scontrol.rep1.type=git
        scontrol.rep1.git.url=https://github.com/${{github.repository}}
        scontrol.git.exec=git
        logging.verbose=true
        dtp.additional.settings=report.coverage.images\=all;cpptest_ut
        report.dtp.publish=${{vars.DTP_PUBLISH}}" >> cpptestcli.properties

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}
      run: cmake -DCPPTEST_COVERAGE=ON -DCPPTEST_HOME=$CPPTEST_CT -S . -B build

    - name: Build 
      working-directory: ${{github.workspace}}
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build build

    - name: Run Tests
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: |
        rm -rf /cpptest-coverage/ATM_Cpp14_lib/ATM_Cpp14_lib.clog 
        rm -rf gtest_results.xml
        ./atm_gtest --gtest_output=xml:atm_gtest_results.xml
      continue-on-error: true

    - name: Generate Reports
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: make cpptestcov-compute cpptestcov-suppress cpptestcov-report 
    
#    - name: Setup Pages
#      uses: actions/configure-pages@v5

    - name: Archive reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: CpptestReports
        include-hidden-files: true
        path: |
          ${{github.workspace}}/.coverage/*.*

#    - name: Upload artifact
#      uses: actions/upload-pages-artifact@v3
#      with:
        # Upload coverage reports
#        path: ${{github.workspace}}/.coverage

    - name: Publish Reports to DTP
      working-directory: ${{github.workspace}}
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run:  cpptestcov report dtp -settings cpptestcli.properties -property build.id=${build_id} -property dtp.project=${DTP_PROJECT} .coverage build/atm_gtest_results.xml
    
    - name: Line Coverage Quality Gate
      working-directory: ${{github.workspace}}
      shell: bash
      # Query for project's coverage and compare with the gate requirements
      run: NUMBER=$(cpptestcov query -coverage LC .coverage) && if [ $NUMBER -lt $LINE_COV_GATE ]; then echo "Line coverage quality gate failed"; echo "Expected result $LINE_COV_GATE%, achieved $NUMBER%"; false; else echo "Line coverage quality gate passed with $NUMBER% (required $LINE_COV_GATE%)"; true; fi      
      
    - name: MCDC Coverage Quality Gate
      working-directory: ${{github.workspace}}
      shell: bash
      # Query for project's coverage and compare with the gate requirements
      run: NUMBER=$(cpptestcov query -coverage MCDC .coverage) && if [ $NUMBER -lt $MCDC_COV_GATE ]; then echo "MCDC coverage quality gate failed"; echo "Expected result $MCDC_COV_GATE%, achieved $NUMBER%"; false; else echo "MC/DC coverage quality gate passed with $NUMBER% (required $MCDC_COV_GATE%)"; true; fi  